### PR TITLE
Better Documentation of Limits

### PR DESCRIPTION
**Pull request by WillKoehrsen**
- Improves documentation of API limits by including mention of `limit` in the `README`
- Adds `limit` to all queries in example notebooks

### CODE REVIEW

**Comment by WillKoehrsen** [comment]
I'm in favor of setting a default limit of 50_000 for `get_dataset`.

**Comment by WillKoehrsen** [comment]
Not sure exactly what invisible means in this context. The default would be set in the client. Instead of

```python
def get_dataset(
    self,
    dataset,
    ...
    limit=None,
):
```

we'd define:

```python
def get_dataset(
    self,
    dataset,
    ...
    limit=50_000,
):
```

You could still query without a limit by calling `get_dataset(..., limit=None)`.

It's a big change, yes, but:

1. It's better for users so they don't unknowingly blow past their limits
2. It's better for us because our systems won't be taxed as heavily
3. This will only affect users when they upgrade the library.

**Comment by WillKoehrsen** [comment]
Fair enough, I can see how having to remove the limit on every query would disrupt your workflow. I'm mostly concerned with people new to the library whose first query is `client.get_dataset("ercot_lmp_by_bus")` and a few minutes later they've used their entire monthly rows allowance.

**Comment by WillKoehrsen** [comment]
> I can see how having to remove the limit on every query would disrupt your workflow

One way around this would be a class parameter you pass to the client constructor to disable all default limits. You'd instantiate the client with `client = GridStatusClient(disable_default_limit=True)` and then you wouldn't have to set `limit=None` for all queries.

That would complicate client usage a little bit though.

**Comment by kmax12** [comment]
What about requiring a start and end date? Or at the very least a start date so it's still easy to get all date up to present as that is a common use case 

Maybe a special value for start if you want the beginning of the dataset.

I think this would cut down on people accidentally pulling too much data.

**Comment by WillKoehrsen** [comment]
> What about requiring a start and end date? 

I'm not sure that would solve the issue. Most of the problematic queries I've seen have used a start and end, but they were on large datasets. For example, one recent query set a start and end date one month apart and would have returned 50 million rows had it succeeded.

**Comment by WillKoehrsen** [comment]
Can we merge this without any changes to the default `limit` behavior (no limit)?

**Review by kmax12 — APPROVED** [review]

**Comment by WillKoehrsen** [comment]
Reran the notebooks before merging.

**Pull request merged**
